In [1]:
### Datos de la OCDE

In [6]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd

In [10]:
OCDE=pd.read_csv('BLI.csv')
print((OCDE))

     LOCATION          Country INDICATOR  \
0         AUS        Australia   JE_LMIS
1         AUT          Austria   JE_LMIS
2         BEL          Belgium   JE_LMIS
3         CAN           Canada   JE_LMIS
4         CZE   Czech Republic   JE_LMIS
5         DNK          Denmark   JE_LMIS
6         FIN          Finland   JE_LMIS
7         FRA           France   JE_LMIS
8         DEU          Germany   JE_LMIS
9         GRC           Greece   JE_LMIS
10        HUN          Hungary   JE_LMIS
11        ISL          Iceland   JE_LMIS
12        IRL          Ireland   JE_LMIS
13        ITA            Italy   JE_LMIS
14        JPN            Japan   JE_LMIS
15        KOR            Korea   JE_LMIS
16        LUX       Luxembourg   JE_LMIS
17        MEX           Mexico   JE_LMIS
18        NLD      Netherlands   JE_LMIS
19        NZL      New Zealand   JE_LMIS
20        NOR           Norway   JE_LMIS
21        POL           Poland   JE_LMIS
22        PRT         Portugal   JE_LMIS
23        SVK  Slovak Republic   JE_LMIS
24        ESP            Spain   JE_LMIS
25        SWE           Sweden   JE_LMIS
26        CHE      Switzerland   JE_LMIS
27        TUR           Turkey   JE_LMIS
28        GBR   United Kingdom   JE_LMIS
29        USA    United States   JE_LMIS
...       ...              ...       ...
3368      GRC           Greece   WL_TNOW
3369      HUN          Hungary   WL_TNOW
3370      ISL          Iceland   WL_TNOW
3371      IRL          Ireland   WL_TNOW
3372      ITA            Italy   WL_TNOW
3373      JPN            Japan   WL_TNOW
3374      KOR            Korea   WL_TNOW
3375      LUX       Luxembourg   WL_TNOW
3376      MEX           Mexico   WL_TNOW
3377      NLD      Netherlands   WL_TNOW
3378      NZL      New Zealand   WL_TNOW
3379      NOR           Norway   WL_TNOW
3380      POL           Poland   WL_TNOW
3381      PRT         Portugal   WL_TNOW
3382      SVK  Slovak Republic   WL_TNOW
3383      ESP            Spain   WL_TNOW
3384      SWE           Sweden   WL_TNOW
3385      CHE      Switzerland   WL_TNOW
3386      TUR           Turkey   WL_TNOW
3387      GBR   United Kingdom   WL_TNOW
3388      USA    United States   WL_TNOW
3389      BRA           Brazil   WL_TNOW
3390      CHL            Chile   WL_TNOW
3391      EST          Estonia   WL_TNOW
3392      ISR           Israel   WL_TNOW
3393      LVA           Latvia   WL_TNOW
3394      RUS           Russia   WL_TNOW
3395      SVN         Slovenia   WL_TNOW
3396      ZAF     South Africa   WL_TNOW
3397     OECD     OECD - Total   WL_TNOW

                                      Indicator MEASURE Measure INEQUALITY  \
0                      Labour market insecurity       L   Value        TOT
1                      Labour market insecurity       L   Value        TOT
2                      Labour market insecurity       L   Value        TOT
3                      Labour market insecurity       L   Value        TOT
4                      Labour market insecurity       L   Value        TOT
5                      Labour market insecurity       L   Value        TOT
6                      Labour market insecurity       L   Value        TOT
7                      Labour market insecurity       L   Value        TOT
8                      Labour market insecurity       L   Value        TOT
9                      Labour market insecurity       L   Value        TOT
10                     Labour market insecurity       L   Value        TOT
11                     Labour market insecurity       L   Value        TOT
12                     Labour market insecurity       L   Value        TOT
13                     Labour market insecurity       L   Value        TOT
14                     Labour market insecurity       L   Value        TOT
15                     Labour market insecurity       L   Value        TOT
16                     Labour market insecurity       L   Value        TOT
17                     Labour market insecurity       L   Value        TOT
18                     Labour market insecurity       L   Value        TOT
19                     Labour market insecurity       L   Value        TOT
20                     Labour market insecurity       L   Value        TOT
21                     Labour market insecurity       L   Value        TOT
22                     Labour market insecurity       L   Value        TOT
23                     Labour market insecurity       L   Value        TOT
24                     Labour market insecurity       L   Value        TOT
25                     Labour market insecurity       L   Value        TOT
26                     Labour market insecurity       L   Value        TOT
27                     Labour market insecurity       L   Value        TOT
28                     Labour market insecurity       L   Value        TOT
29                     Labour market insecurity       L   Value        TOT
...                                         ...     ...     ...        ...
3368  Time devoted to leisure and personal care       L   Value        WMN
3369  Time devoted to leisure and personal care       L   Value        WMN
3370  Time devoted to leisure and personal care       L   Value        WMN
3371  Time devoted to leisure and personal care       L   Value        WMN
3372  Time devoted to leisure and personal care       L   Value        WMN
3373  Time devoted to leisure and personal care       L   Value        WMN
3374  Time devoted to leisure and personal care       L   Value        WMN
3375  Time devoted to leisure and personal care       L   Value        WMN
3376  Time devoted to leisure and personal care       L   Value        WMN
3377  Time devoted to leisure and personal care       L   Value        WMN
3378  Time devoted to leisure and personal care       L   Value        WMN
3379  Time devoted to leisure and personal care       L   Value        WMN
3380  Time devoted to leisure and personal care       L   Value        WMN
3381  Time devoted to leisure and personal care       L   Value        WMN
3382  Time devoted to leisure and personal care       L   Value        WMN
3383  Time devoted to leisure and personal care       L   Value        WMN
3384  Time devoted to leisure and personal care       L   Value        WMN
3385  Time devoted to leisure and personal care       L   Value        WMN
3386  Time devoted to leisure and personal care       L   Value        WMN
3387  Time devoted to leisure and personal care       L   Value        WMN
3388  Time devoted to leisure and personal care       L   Value        WMN
3389  Time devoted to leisure and personal care       L   Value        WMN
3390  Time devoted to leisure and personal care       L   Value        WMN
3391  Time devoted to leisure and personal care       L   Value        WMN
3392  Time devoted to leisure and personal care       L   Value        WMN
3393  Time devoted to leisure and personal care       L   Value        WMN
3394  Time devoted to leisure and personal care       L   Value        WMN
3395  Time devoted to leisure and personal care       L   Value        WMN
3396  Time devoted to leisure and personal care       L   Value        WMN
3397  Time devoted to leisure and personal care       L   Value        WMN

     Inequality Unit Code        Unit  PowerCode Code PowerCode  \
0         Total        PC  Percentage               0     Units
1         Total        PC  Percentage               0     Units
2         Total        PC  Percentage               0     Units
3         Total        PC  Percentage               0     Units
4         Total        PC  Percentage               0     Units
5         Total        PC  Percentage               0     Units
6         Total        PC  Percentage               0     Units
7         Total        PC  Percentage               0     Units
8         Total        PC  Percentage               0     Units
9         Total        PC  Percentage               0     Units
10        Total        PC  Percentage               0     Units
11        Total        PC  Percentage               0     Units
12        Total        PC  Percentage               0     Units
13        Total        PC  Percentage               0     Units
14        Total        PC  Percentage               0     Units
15        Total        PC  Percentage               0     Units
16        Total        PC  Percentage               0     Units
17        Total        PC  Percentage               0     Units
18        Total        PC  Percentage               0     Units
19        Total        PC  Percentage               0     Units
20        Total        PC  Percentage               0     Units
21        Total        PC  Percentage               0     Units
22        Total        PC  Percentage               0     Units
23        Total        PC  Percentage               0     Units
24        Total        PC  Percentage               0     Units
25        Total        PC  Percentage               0     Units
26        Total        PC  Percentage               0     Units
27        Total        PC  Percentage               0     Units
28        Total        PC  Percentage               0     Units
29        Total        PC  Percentage               0     Units
...         ...       ...         ...             ...       ...
3368      Women      HOUR       Hours               0     Units
3369      Women      HOUR       Hours               0     Units
3370      Women      HOUR       Hours               0     Units
3371      Women      HOUR       Hours               0     Units
3372      Women      HOUR       Hours               0     Units
3373      Women      HOUR       Hours               0     Units
3374      Women      HOUR       Hours               0     Units
3375      Women      HOUR       Hours               0     Units
3376      Women      HOUR       Hours               0     Units
3377      Women      HOUR       Hours               0     Units
3378      Women      HOUR       Hours               0     Units
3379      Women      HOUR       Hours               0     Units
3380      Women      HOUR       Hours               0     Units
3381      Women      HOUR       Hours               0     Units
3382      Women      HOUR       Hours               0     Units
3383      Women      HOUR       Hours               0     Units
3384      Women      HOUR       Hours               0     Units
3385      Women      HOUR       Hours               0     Units
3386      Women      HOUR       Hours               0     Units
3387      Women      HOUR       Hours               0     Units
3388      Women      HOUR       Hours               0     Units
3389      Women      HOUR       Hours               0     Units
3390      Women      HOUR       Hours               0     Units
3391      Women      HOUR       Hours               0     Units
3392      Women      HOUR       Hours               0     Units
3393      Women      HOUR       Hours               0     Units
3394      Women      HOUR       Hours               0     Units
3395      Women      HOUR       Hours               0     Units
3396      Women      HOUR       Hours               0     Units
3397      Women      HOUR       Hours               0     Units

      Reference Period Code  Reference Period  Value Flag Codes  \
0                       NaN               NaN   4.30        NaN
1                       NaN               NaN   2.70        NaN
2                       NaN               NaN   4.80        NaN
3                       NaN               NaN   3.90        NaN
4                       NaN               NaN   1.80        NaN
5                       NaN               NaN   2.30        NaN
6                       NaN               NaN   2.70        NaN
7                       NaN               NaN   5.00        NaN
8                       NaN               NaN   2.00        NaN
9                       NaN               NaN  17.40        NaN
10                      NaN               NaN   4.80        NaN
11                      NaN               NaN   2.60        NaN
12                      NaN               NaN   2.10        NaN
13                      NaN               NaN   8.10        NaN
14                      NaN               NaN   1.50        NaN
15                      NaN               NaN   2.40        NaN
16                      NaN               NaN   3.20        NaN
17                      NaN               NaN   4.60        NaN
18                      NaN               NaN   2.10        NaN
19                      NaN               NaN   4.90        NaN
20                      NaN               NaN   2.70        NaN
21                      NaN               NaN   4.30        NaN
22                      NaN               NaN   6.50        NaN
23                      NaN               NaN   6.70        NaN
24                      NaN               NaN  17.30        NaN
25                      NaN               NaN   5.70        NaN
26                      NaN               NaN   1.80        NaN
27                      NaN               NaN  13.00        NaN
28                      NaN               NaN   2.60        NaN
29                      NaN               NaN   3.80        NaN
...                     ...               ...    ...        ...
3368                    NaN               NaN  14.42          E
3369                    NaN               NaN  14.82          E
3370                    NaN               NaN  13.87          E
3371                    NaN               NaN  15.06          E
3372                    NaN               NaN  14.29        NaN
3373                    NaN               NaN  14.53        NaN
3374                    NaN               NaN  14.00        NaN
3375                    NaN               NaN  14.92          E
3376                    NaN               NaN  12.39          E
3377                    NaN               NaN  15.71          E
3378                    NaN               NaN  14.95        NaN
3379                    NaN               NaN  15.65        NaN
3380                    NaN               NaN  14.08        NaN
3381                    NaN               NaN  14.64          E
3382                    NaN               NaN  14.77          E
3383                    NaN               NaN  15.48        NaN
3384                    NaN               NaN  15.23        NaN
3385                    NaN               NaN  14.78          E
3386                    NaN               NaN  12.22          E
3387                    NaN               NaN  14.86        NaN
3388                    NaN               NaN  14.39        NaN
3389                    NaN               NaN  14.18          E
3390                    NaN               NaN  14.66          E
3391                    NaN               NaN  14.43        NaN
3392                    NaN               NaN  13.63          E
3393                    NaN               NaN  13.45        NaN
3394                    NaN               NaN  14.66          E
3395                    NaN               NaN  14.17        NaN
3396                    NaN               NaN  14.37        NaN
3397                    NaN               NaN  14.60        NaN

                Flags
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
6                 NaN
7                 NaN
8                 NaN
9                 NaN
10                NaN
11                NaN
12                NaN
13                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
...               ...
3368  Estimated value
3369  Estimated value
3370  Estimated value
3371  Estimated value
3372              NaN
3373              NaN
3374              NaN
3375  Estimated value
3376  Estimated value
3377  Estimated value
3378              NaN
3379              NaN
3380              NaN
3381  Estimated value
3382  Estimated value
3383              NaN
3384              NaN
3385  Estimated value
3386  Estimated value
3387              NaN
3388              NaN
3389  Estimated value
3390  Estimated value
3391              NaN
3392  Estimated value
3393              NaN
3394  Estimated value
3395              NaN
3396              NaN
3397              NaN

[3398 rows x 17 columns]

### Análisis inicial

# Número de países incluídos en el reporte

In [11]:
#Paises 

Paises=OCDE["Country"].unique()

pd.DataFrame(Paises)

                  0
0         Australia
1           Austria
2           Belgium
3            Canada
4    Czech Republic
5           Denmark
6           Finland
7            France
8           Germany
9            Greece
10          Hungary
11          Iceland
12          Ireland
13            Italy
14            Japan
15            Korea
16       Luxembourg
17           Mexico
18      Netherlands
19      New Zealand
20           Norway
21           Poland
22         Portugal
23  Slovak Republic
24            Spain
25           Sweden
26      Switzerland
27           Turkey
28   United Kingdom
29    United States
30           Brazil
31            Chile
32          Estonia
33           Israel
34           Latvia
35           Russia
36         Slovenia
37     South Africa
38     OECD - Total

In [12]:
Cantidad_paises=len(OCDE["Country"].unique())-2
print(Cantidad_paises)

37

In [13]:
#cuantos paises
len(OCDE["Country"].unique())-1

38

## En la bases de datos se presentan las siguientes unidades

In [14]:
len(OCDE["Unit"].unique())

7

In [15]:
Unidad=OCDE["Unit"].unique()
pd.DataFrame(Unidad)

                            0
0                  Percentage
1               Average score
2                       Ratio
3                   US Dollar
4                       Years
5  Micrograms per cubic metre
6                       Hours

### Indicadores medidos y cuántos son

In [16]:
Indicadores=OCDE["Indicator"].unique()
pd.DataFrame(Indicadores)

                                                    0
0                            Labour market insecurity
1   Stakeholder engagement for developing regulations
2                 Feeling safe walking alone at night
3                  Dwellings without basic facilities
4                                 Housing expenditure
5                                    Rooms per person
6            Household net adjusted disposable income
7                      Household net financial wealth
8                                     Employment rate
9                         Long-term unemployment rate
10                                  Personal earnings
11                         Quality of support network
12                             Educational attainment
13                                     Student skills
14                                 Years in education
15                                      Air pollution
16                                      Water quality
17                                      Voter turnout
18                                    Life expectancy
19                               Self-reported health
20                                  Life satisfaction
21                                      Homicide rate
22                  Employees working very long hours
23          Time devoted to leisure and personal care

In [17]:
len(OCDE["Indicator"].unique())

24

## Descripción básica de los indicadores númericos

In [18]:

OCDE.describe()

       PowerCode Code  Reference Period Code  Reference Period          Value
count          3398.0                    0.0               0.0    3398.000000
mean              0.0                    NaN               NaN    5353.200309
std               0.0                    NaN               NaN   15832.099269
min               0.0                    NaN               NaN       0.000000
25%               0.0                    NaN               NaN       7.000000
50%               0.0                    NaN               NaN      62.000000
75%               0.0                    NaN               NaN      91.000000
max               0.0                    NaN               NaN  176076.000000

#### Presentación más limpia

##¿Podemos eliminar algunas columnas de nuestra base de datos sin perder información importante? Presenta la tabla y explica por qué eliminste dichas columnas

In [21]:
Nueva_table=OCDE
Nueva_nueva=Nueva_table.drop(["MEASURE","INEQUALITY","Unit Code", "PowerCode Code","Unit Code","Reference Period Code","Flag Codes","Flags"],axis=1)

In [22]:
pd.DataFrame(Nueva_nueva)

,LOCATION,Country,INDICATOR,Indicator,Measure,Inequality,Unit,PowerCode,Reference Period,Value
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.90
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
5,DNK,Denmark,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.30
6,FIN,Finland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
7,FRA,France,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.00
8,DEU,Germany,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.00
9,GRC,Greece,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.40
10,HUN,Hungary,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
11,ISL,Iceland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
12,IRL,Ireland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
13,ITA,Italy,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,8.10
14,JPN,Japan,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.50
15,KOR,Korea,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.40
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.20
17,MEX,Mexico,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.60
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.90
20,NOR,Norway,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
21,POL,Poland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
22,PRT,Portugal,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.50
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.70
24,ESP,Spain,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.30
25,SWE,Sweden,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.70
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
27,TUR,Turkey,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,13.00
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
29,USA,United States,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.80
...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.42
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.82
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.87
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.06
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.29
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.53
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.00
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.92
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.39
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.71
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.95
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.65
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.08
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.64
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.77
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.48
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.23
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.78
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.22
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.86
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.39
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.18
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.43
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.63
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.45
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.17
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.37
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.60

¿Puedes cambiar en nombre de las columnas a español?

In [23]:
Nueva_nueva.rename(columns={ "Country":"País", "Indicator":"Indicador", "Measure":"Medida","Inequality":"Inequidad", "Unit":"Unidad","Reference Period":"Periodo de Referencia","Value":"Valor"})

,LOCATION,País,INDICATOR,Indicador,Medida,Inequidad,Unidad,PowerCode,Periodo de Referencia,Valor
0,AUS,Australia,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
1,AUT,Austria,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
2,BEL,Belgium,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
3,CAN,Canada,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.90
4,CZE,Czech Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
5,DNK,Denmark,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.30
6,FIN,Finland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
7,FRA,France,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.00
8,DEU,Germany,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.00
9,GRC,Greece,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.40
10,HUN,Hungary,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.80
11,ISL,Iceland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
12,IRL,Ireland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
13,ITA,Italy,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,8.10
14,JPN,Japan,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.50
15,KOR,Korea,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.40
16,LUX,Luxembourg,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.20
17,MEX,Mexico,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.60
18,NLD,Netherlands,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.10
19,NZL,New Zealand,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.90
20,NOR,Norway,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.70
21,POL,Poland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,4.30
22,PRT,Portugal,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.50
23,SVK,Slovak Republic,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,6.70
24,ESP,Spain,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,17.30
25,SWE,Sweden,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,5.70
26,CHE,Switzerland,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,1.80
27,TUR,Turkey,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,13.00
28,GBR,United Kingdom,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,2.60
29,USA,United States,JE_LMIS,Labour market insecurity,Value,Total,Percentage,Units,NaN,3.80
...,...,...,...,...,...,...,...,...,...,...
3368,GRC,Greece,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.42
3369,HUN,Hungary,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.82
3370,ISL,Iceland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.87
3371,IRL,Ireland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.06
3372,ITA,Italy,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.29
3373,JPN,Japan,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.53
3374,KOR,Korea,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.00
3375,LUX,Luxembourg,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.92
3376,MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.39
3377,NLD,Netherlands,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.71
3378,NZL,New Zealand,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.95
3379,NOR,Norway,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.65
3380,POL,Poland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.08
3381,PRT,Portugal,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.64
3382,SVK,Slovak Republic,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.77
3383,ESP,Spain,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.48
3384,SWE,Sweden,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,15.23
3385,CHE,Switzerland,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.78
3386,TUR,Turkey,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,12.22
3387,GBR,United Kingdom,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.86
3388,USA,United States,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.39
3389,BRA,Brazil,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.18
3390,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3391,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.43
3392,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.63
3393,LVA,Latvia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,13.45
3394,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.66
3395,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.17
3396,ZAF,South Africa,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.37
3397,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,Value,Women,Hours,Units,NaN,14.60

###Parte 4 - Búsqueda de datos (30 puntos)

In [24]:
OCDE2=OCDE
OCDE3=OCDE2.set_index(["LOCATION"])

In [25]:

Mexico=OCDE3.loc["MEX"]
Mexico[["Indicator"]]

pd.DataFrame(Mexico)

,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,,
MEX,Mexico,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,Mexico,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
MEX,Mexico,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,Mexico,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,Mexico,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,Mexico,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
MEX,Mexico,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,Mexico,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
MEX,Mexico,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
MEX,Mexico,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
MEX,Mexico,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,Mexico,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,Mexico,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,Mexico,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,Mexico,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
MEX,Mexico,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
MEX,Mexico,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
MEX,Mexico,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
MEX,Mexico,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
MEX,Mexico,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
MEX,Mexico,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
MEX,Mexico,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

In [29]:
OCDE4=Mexico.drop(["Country"],axis=1)
pd.DataFrame(OCDE4)

,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
LOCATION,,,,,,,,,,,,,,,
MEX,JE_LMIS,Labour market insecurity,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.60,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,3.50,NaN,NaN
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,CG_SENG,Stakeholder engagement for developing regulations,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,3.50,E,Estimated value
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.90,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,48.20,NaN,NaN
MEX,PS_FSAFEN,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.60,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,HO_BASE,Dwellings without basic facilities,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,4.20,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,21.00,NaN,NaN
MEX,HO_HISH,Housing expenditure,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_HISH,Housing expenditure,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,21.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,1.00,NaN,NaN
MEX,HO_NUMR,Rooms per person,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,1.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,13891.00,NaN,NaN
MEX,IW_HADI,Household net adjusted disposable income,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,13891.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,Units,NaN,NaN,35912.00,E,Estimated value
MEX,IW_HADI,Household net adjusted disposable income,L,Value,LW,Low,USD,US Dollar,0,Units,NaN,NaN,3444.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,TOT,Total,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,MN,Men,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,IW_HNFW,Household net financial wealth,L,Value,WMN,Women,USD,US Dollar,0,Units,NaN,NaN,4750.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,79.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.00,NaN,NaN
MEX,JE_EMPL,Employment rate,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,80.00,E,Estimated value
MEX,JE_EMPL,Employment rate,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,65.00,E,Estimated value
MEX,JE_LTUR,Long-term unemployment rate,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,0.08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MEX,EQ_WATER,Water quality,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,EQ_WATER,Water quality,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,68.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.00,NaN,NaN
MEX,CG_VOTO,Voter turnout,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,CG_VOTO,Voter turnout,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,63.00,E,Estimated value
MEX,HS_LEB,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.00,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,MN,Men,YR,Years,0,Units,NaN,NaN,72.30,NaN,NaN
MEX,HS_LEB,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.70,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,67.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,64.00,NaN,NaN
MEX,HS_SFRH,Self-reported health,L,Value,HGH,High,PC,Percentage,0,Units,NaN,NaN,78.00,E,Estimated value
MEX,HS_SFRH,Self-reported health,L,Value,LW,Low,PC,Percentage,0,Units,NaN,NaN,57.00,E,Estimated value
MEX,SW_LIFS,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,MN,Men,AVSCORE,Average score,0,Units,NaN,NaN,6.50,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,WMN,Women,AVSCORE,Average score,0,Units,NaN,NaN,6.60,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,HGH,High,AVSCORE,Average score,0,Units,NaN,NaN,7.40,NaN,NaN
MEX,SW_LIFS,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.10,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,TOT,Total,RATIO,Ratio,0,Units,NaN,NaN,17.90,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,MN,Men,RATIO,Ratio,0,Units,NaN,NaN,33.50,NaN,NaN
MEX,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,Units,NaN,NaN,4.20,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,29.48,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,MN,Men,PC,Percentage,0,Units,NaN,NaN,36.27,NaN,NaN
MEX,WL_EWLH,Employees working very long hours,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,18.39,NaN,NaN
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,TOT,Total,HOUR,Hours,0,Units,NaN,NaN,12.74,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,MN,Men,HOUR,Hours,0,Units,NaN,NaN,13.03,E,Estimated value
MEX,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,Units,NaN,NaN,12.39,E,Estimated value

###Muestra los países con esperanza de vida femenina mayor al promedio general y sus datos

In [28]:
OCDE5=OCDE
OCDE_vida=OCDE5.set_index("INDICATOR")
expectativa=OCDE_vida.loc["HS_LEB"]
pd.DataFrame(expectativa)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
INDICATOR,,,,,,,,,,,,,,,,
HS_LEB,AUS,Australia,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
HS_LEB,AUT,Austria,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.3,NaN,NaN
HS_LEB,BEL,Belgium,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
HS_LEB,CAN,Canada,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
HS_LEB,CZE,Czech Republic,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.7,NaN,NaN
HS_LEB,DNK,Denmark,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.8,NaN,NaN
HS_LEB,FIN,Finland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,FRA,France,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,DEU,Germany,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
HS_LEB,GRC,Greece,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.1,NaN,NaN
HS_LEB,HUN,Hungary,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.7,NaN,NaN
HS_LEB,ISL,Iceland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.5,NaN,NaN
HS_LEB,IRL,Ireland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.5,NaN,NaN
HS_LEB,ITA,Italy,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.6,NaN,NaN
HS_LEB,JPN,Japan,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
HS_LEB,KOR,Korea,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.1,NaN,NaN
HS_LEB,LUX,Luxembourg,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,MEX,Mexico,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,75.0,NaN,NaN
HS_LEB,NLD,Netherlands,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,NZL,New Zealand,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
HS_LEB,NOR,Norway,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.4,NaN,NaN
HS_LEB,POL,Poland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,77.6,NaN,NaN
HS_LEB,PRT,Portugal,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
HS_LEB,SVK,Slovak Republic,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
HS_LEB,ESP,Spain,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
HS_LEB,SWE,Sweden,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,82.3,NaN,NaN
HS_LEB,CHE,Switzerland,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,83.0,NaN,NaN
HS_LEB,TUR,Turkey,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.0,NaN,NaN
HS_LEB,GBR,United Kingdom,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,81.0,NaN,NaN
HS_LEB,USA,United States,Life expectancy,L,Value,TOT,Total,YR,Years,0,Units,NaN,NaN,78.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HS_LEB,GRC,Greece,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
HS_LEB,HUN,Hungary,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
HS_LEB,ISL,Iceland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
HS_LEB,IRL,Ireland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
HS_LEB,ITA,Italy,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
HS_LEB,JPN,Japan,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
HS_LEB,KOR,Korea,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
HS_LEB,LUX,Luxembourg,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
HS_LEB,MEX,Mexico,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
HS_LEB,NLD,Netherlands,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
HS_LEB,NZL,New Zealand,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
HS_LEB,NOR,Norway,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
HS_LEB,POL,Poland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
HS_LEB,PRT,Portugal,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
HS_LEB,SVK,Slovak Republic,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
HS_LEB,ESP,Spain,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
HS_LEB,SWE,Sweden,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
HS_LEB,CHE,Switzerland,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
HS_LEB,TUR,Turkey,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
HS_LEB,GBR,United Kingdom,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
HS_LEB,USA,United States,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
HS_LEB,BRA,Brazil,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
HS_LEB,CHL,Chile,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
HS_LEB,EST,Estonia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
HS_LEB,ISR,Israel,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
HS_LEB,LVA,Latvia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
HS_LEB,RUS,Russia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
HS_LEB,SVN,Slovenia,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
HS_LEB,ZAF,South Africa,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
HS_LEB,OECD,OECD - Total,Life expectancy,L,Value,WMN,Women,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

In [30]:
esperanza=expectativa.set_index("Inequality")

In [31]:
mujeres=esperanza.loc["Women"]
pd.DataFrame(mujeres)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Women,AUS,Australia,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.5,NaN,NaN
Women,AUT,Austria,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,BEL,Belgium,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,CAN,Canada,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.6,NaN,NaN
Women,CZE,Czech Republic,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Women,DNK,Denmark,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN
Women,FIN,Finland,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.4,NaN,NaN
Women,FRA,France,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.5,NaN,NaN
Women,DEU,Germany,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.1,NaN,NaN
Women,GRC,Greece,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.7,NaN,NaN
Women,HUN,Hungary,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.0,NaN,NaN
Women,ISL,Iceland,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.8,NaN,NaN
Women,IRL,Ireland,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,ITA,Italy,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.9,NaN,NaN
Women,JPN,Japan,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,87.1,NaN,NaN
Women,KOR,Korea,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.2,NaN,NaN
Women,LUX,Luxembourg,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.7,NaN,NaN
Women,MEX,Mexico,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,77.7,NaN,NaN
Women,NLD,Netherlands,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.2,NaN,NaN
Women,NZL,New Zealand,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.4,NaN,NaN
Women,NOR,Norway,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.2,NaN,NaN
Women,POL,Poland,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.6,NaN,NaN
Women,PRT,Portugal,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.3,NaN,NaN
Women,SVK,Slovak Republic,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.2,NaN,NaN
Women,ESP,Spain,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.8,NaN,NaN
Women,SWE,Sweden,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,CHE,Switzerland,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,85.1,NaN,NaN
Women,TUR,Turkey,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,80.7,NaN,NaN
Women,GBR,United Kingdom,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.8,NaN,NaN
Women,USA,United States,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.2,NaN,NaN
Women,BRA,Brazil,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,78.5,NaN,NaN
Women,CHL,Chile,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,81.7,NaN,NaN
Women,EST,Estonia,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.2,NaN,NaN
Women,ISR,Israel,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,84.1,NaN,NaN
Women,LVA,Latvia,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,79.5,NaN,NaN
Women,RUS,Russia,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,76.7,NaN,NaN
Women,SVN,Slovenia,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,83.9,NaN,NaN
Women,ZAF,South Africa,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,59.5,NaN,NaN
Women,OECD,OECD - Total,Life expectancy,L,Value,WMN,YR,Years,0,Units,NaN,NaN,82.7,NaN,NaN

In [32]:
mujeres.describe()

       PowerCode Code  Reference Period Code  Reference Period      Value
count            39.0                    0.0               0.0  39.000000
mean              0.0                    NaN               NaN  82.241026
std               0.0                    NaN               NaN   4.378880
min               0.0                    NaN               NaN  59.500000
25%               0.0                    NaN               NaN  81.600000
50%               0.0                    NaN               NaN  83.400000
75%               0.0                    NaN               NaN  84.250000
max               0.0                    NaN               NaN  87.100000

In [33]:
#variable promedio de vida
Promedio_de_vida=82.24 

total=mujeres.count()
print(total)

LOCATION                 39
Country                  39
Indicator                39
MEASURE                  39
Measure                  39
INEQUALITY               39
Unit Code                39
Unit                     39
PowerCode Code           39
PowerCode                39
Reference Period Code     0
Reference Period          0
Value                    39
Flag Codes                0
Flags                     0
dtype: int64

In [34]:
# creación panda para index

mujer_esperanza=mujeres["Value"]
pd.DataFrame(mujer_esperanza)

            Value
Inequality
Women        84.5
Women        83.7
Women        83.4
Women        83.6
Women        81.6
Women        82.7
Women        84.4
Women        85.5
Women        83.1
Women        83.7
Women        79.0
Women        83.8
Women        83.4
Women        84.9
Women        87.1
Women        85.2
Women        84.7
Women        77.7
Women        83.2
Women        83.4
Women        84.2
Women        81.6
Women        84.3
Women        80.2
Women        85.8
Women        84.1
Women        85.1
Women        80.7
Women        82.8
Women        81.2
Women        78.5
Women        81.7
Women        82.2
Women        84.1
Women        79.5
Women        76.7
Women        83.9
Women        59.5
Women        82.7

In [36]:
#parámetro para esperanza de vida
Esperanza_vida_promedio=82.24
total=mujer_esperanza.count()

In [40]:
P_V=sum(mujer_esperanza>Esperanza_vida_promedio)
Promedio=P_V/total

print("Existen", P_V,"países con expectativa mayor al promedio", "de un total de", total)

Existen 26 países con expectativa mayor al promedio de un total de 39

In [56]:
### Cuales países son:

mujeres_nueva=mujeres.drop(["MEASURE","Unit Code","Flags","Measure","INEQUALITY","LOCATION", "PowerCode Code","Reference Period Code","Flag Codes","Reference Period","PowerCode","Unit"],axis=1)
mujer_esperanza_paises=mujeres_nueva[mujeres_nueva["Value"]>82.24]

#Paises en orden 
Paises_ordeandos=mujer_esperanza_paises.sort_values(by=["Value"],axis=0, ascending=False)
pd.DataFrame(Paises_ordeandos)

                   Country        Indicator  Value
Inequality
Women                Japan  Life expectancy   87.1
Women                Spain  Life expectancy   85.8
Women               France  Life expectancy   85.5
Women                Korea  Life expectancy   85.2
Women          Switzerland  Life expectancy   85.1
Women                Italy  Life expectancy   84.9
Women           Luxembourg  Life expectancy   84.7
Women            Australia  Life expectancy   84.5
Women              Finland  Life expectancy   84.4
Women             Portugal  Life expectancy   84.3
Women               Norway  Life expectancy   84.2
Women               Israel  Life expectancy   84.1
Women               Sweden  Life expectancy   84.1
Women             Slovenia  Life expectancy   83.9
Women              Iceland  Life expectancy   83.8
Women               Greece  Life expectancy   83.7
Women              Austria  Life expectancy   83.7
Women               Canada  Life expectancy   83.6
Women          New Zealand  Life expectancy   83.4
Women              Belgium  Life expectancy   83.4
Women              Ireland  Life expectancy   83.4
Women          Netherlands  Life expectancy   83.2
Women              Germany  Life expectancy   83.1
Women       United Kingdom  Life expectancy   82.8
Women              Denmark  Life expectancy   82.7
Women         OECD - Total  Life expectancy   82.7

####Muestra los países cuya seguridad al caminar en la noche es menor al promedio y sus valores

In [59]:
OCDE6=OCDE
OCDE_esperanza_vida=OCDE6.set_index("INDICATOR")
variable_nueva=OCDE_esperanza_vida.loc["PS_FSAFEN"]
pd.DataFrame(variable_nueva)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
INDICATOR,,,,,,,,,,,,,,,,
PS_FSAFEN,AUS,Australia,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.6,NaN,NaN
PS_FSAFEN,AUT,Austria,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,80.7,NaN,NaN
PS_FSAFEN,BEL,Belgium,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,70.7,NaN,NaN
PS_FSAFEN,CAN,Canada,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,80.9,NaN,NaN
PS_FSAFEN,CZE,Czech Republic,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,68.3,NaN,NaN
PS_FSAFEN,DNK,Denmark,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,83.0,NaN,NaN
PS_FSAFEN,FIN,Finland,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,82.9,NaN,NaN
PS_FSAFEN,FRA,France,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,69.6,NaN,NaN
PS_FSAFEN,DEU,Germany,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
PS_FSAFEN,GRC,Greece,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,61.8,NaN,NaN
PS_FSAFEN,HUN,Hungary,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,50.7,NaN,NaN
PS_FSAFEN,ISL,Iceland,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,87.0,NaN,NaN
PS_FSAFEN,IRL,Ireland,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.5,NaN,NaN
PS_FSAFEN,ITA,Italy,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,58.3,NaN,NaN
PS_FSAFEN,JPN,Japan,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,70.6,NaN,NaN
PS_FSAFEN,KOR,Korea,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,63.9,NaN,NaN
PS_FSAFEN,LUX,Luxembourg,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,72.0,NaN,NaN
PS_FSAFEN,MEX,Mexico,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,45.9,NaN,NaN
PS_FSAFEN,NLD,Netherlands,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,81.2,NaN,NaN
PS_FSAFEN,NZL,New Zealand,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,64.8,NaN,NaN
PS_FSAFEN,NOR,Norway,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,87.7,NaN,NaN
PS_FSAFEN,POL,Poland,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,66.3,NaN,NaN
PS_FSAFEN,PRT,Portugal,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,72.1,NaN,NaN
PS_FSAFEN,SVK,Slovak Republic,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,60.1,NaN,NaN
PS_FSAFEN,ESP,Spain,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,83.1,NaN,NaN
PS_FSAFEN,SWE,Sweden,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
PS_FSAFEN,CHE,Switzerland,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,84.0,NaN,NaN
PS_FSAFEN,TUR,Turkey,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,60.6,NaN,NaN
PS_FSAFEN,GBR,United Kingdom,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,77.4,NaN,NaN
PS_FSAFEN,USA,United States,Feeling safe walking alone at night,L,Value,TOT,Total,PC,Percentage,0,Units,NaN,NaN,74.1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PS_FSAFEN,GRC,Greece,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.1,NaN,NaN
PS_FSAFEN,HUN,Hungary,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,42.0,NaN,NaN
PS_FSAFEN,ISL,Iceland,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.9,NaN,NaN
PS_FSAFEN,IRL,Ireland,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,66.5,NaN,NaN
PS_FSAFEN,ITA,Italy,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.3,NaN,NaN
PS_FSAFEN,JPN,Japan,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,61.4,NaN,NaN
PS_FSAFEN,KOR,Korea,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,58.0,NaN,NaN
PS_FSAFEN,LUX,Luxembourg,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,65.8,NaN,NaN
PS_FSAFEN,MEX,Mexico,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,43.6,NaN,NaN
PS_FSAFEN,NLD,Netherlands,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,71.9,NaN,NaN
PS_FSAFEN,NZL,New Zealand,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.5,NaN,NaN
PS_FSAFEN,NOR,Norway,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.6,NaN,NaN
PS_FSAFEN,POL,Poland,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,57.7,NaN,NaN
PS_FSAFEN,PRT,Portugal,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,61.2,NaN,NaN
PS_FSAFEN,SVK,Slovak Republic,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,51.2,NaN,NaN
PS_FSAFEN,ESP,Spain,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,79.2,NaN,NaN
PS_FSAFEN,SWE,Sweden,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.4,NaN,NaN
PS_FSAFEN,CHE,Switzerland,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,77.7,NaN,NaN
PS_FSAFEN,TUR,Turkey,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.0,NaN,NaN
PS_FSAFEN,GBR,United Kingdom,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,73.9,NaN,NaN
PS_FSAFEN,USA,United States,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.3,NaN,NaN
PS_FSAFEN,BRA,Brazil,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,29.2,NaN,NaN
PS_FSAFEN,CHL,Chile,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,47.3,NaN,NaN
PS_FSAFEN,EST,Estonia,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,59.1,NaN,NaN
PS_FSAFEN,ISR,Israel,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,63.8,NaN,NaN
PS_FSAFEN,LVA,Latvia,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,52.9,NaN,NaN
PS_FSAFEN,RUS,Russia,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,45.3,NaN,NaN
PS_FSAFEN,SVN,Slovenia,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,76.6,NaN,NaN
PS_FSAFEN,ZAF,South Africa,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,28.9,NaN,NaN
PS_FSAFEN,OECD,OECD - Total,Feeling safe walking alone at night,L,Value,WMN,Women,PC,Percentage,0,Units,NaN,NaN,60.8,NaN,NaN

In [60]:
variable_nueva.describe()

       PowerCode Code  Reference Period Code  Reference Period       Value
count           117.0                    0.0               0.0  117.000000
mean              0.0                    NaN               NaN   68.845299
std               0.0                    NaN               NaN   14.706458
min               0.0                    NaN               NaN   28.900000
25%               0.0                    NaN               NaN   60.600000
50%               0.0                    NaN               NaN   70.400000
75%               0.0                    NaN               NaN   79.700000
max               0.0                    NaN               NaN   95.600000

In [62]:
total_población=variable_nueva.set_index("Inequality")

In [63]:
total_total=total_población.loc["Total"]
pd.DataFrame(total_total)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Total,AUS,Australia,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,63.6,NaN,NaN
Total,AUT,Austria,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,80.7,NaN,NaN
Total,BEL,Belgium,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,70.7,NaN,NaN
Total,CAN,Canada,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,80.9,NaN,NaN
Total,CZE,Czech Republic,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,68.3,NaN,NaN
Total,DNK,Denmark,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,83.0,NaN,NaN
Total,FIN,Finland,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,82.9,NaN,NaN
Total,FRA,France,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,69.6,NaN,NaN
Total,DEU,Germany,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
Total,GRC,Greece,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,61.8,NaN,NaN
Total,HUN,Hungary,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,50.7,NaN,NaN
Total,ISL,Iceland,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,87.0,NaN,NaN
Total,IRL,Ireland,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,75.5,NaN,NaN
Total,ITA,Italy,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,58.3,NaN,NaN
Total,JPN,Japan,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,70.6,NaN,NaN
Total,KOR,Korea,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,63.9,NaN,NaN
Total,LUX,Luxembourg,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,72.0,NaN,NaN
Total,MEX,Mexico,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,45.9,NaN,NaN
Total,NLD,Netherlands,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,81.2,NaN,NaN
Total,NZL,New Zealand,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,64.8,NaN,NaN
Total,NOR,Norway,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,87.7,NaN,NaN
Total,POL,Poland,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,66.3,NaN,NaN
Total,PRT,Portugal,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,72.1,NaN,NaN
Total,SVK,Slovak Republic,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,60.1,NaN,NaN
Total,ESP,Spain,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,83.1,NaN,NaN
Total,SWE,Sweden,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,75.9,NaN,NaN
Total,CHE,Switzerland,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,84.0,NaN,NaN
Total,TUR,Turkey,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,60.6,NaN,NaN
Total,GBR,United Kingdom,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,77.4,NaN,NaN
Total,USA,United States,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,74.1,NaN,NaN
Total,BRA,Brazil,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,37.3,NaN,NaN
Total,CHL,Chile,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,51.1,NaN,NaN
Total,EST,Estonia,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,67.2,NaN,NaN
Total,ISR,Israel,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,70.2,NaN,NaN
Total,LVA,Latvia,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,60.7,NaN,NaN
Total,RUS,Russia,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,52.2,NaN,NaN
Total,SVN,Slovenia,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,84.7,NaN,NaN
Total,ZAF,South Africa,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,36.1,NaN,NaN
Total,OECD,OECD - Total,Feeling safe walking alone at night,L,Value,TOT,PC,Percentage,0,Units,NaN,NaN,68.6,NaN,NaN

In [64]:
total_total.describe()

       PowerCode Code  Reference Period Code  Reference Period      Value
count            39.0                    0.0               0.0  39.000000
mean              0.0                    NaN               NaN  68.633333
std               0.0                    NaN               NaN  13.020860
min               0.0                    NaN               NaN  36.100000
25%               0.0                    NaN               NaN  61.250000
50%               0.0                    NaN               NaN  70.200000
75%               0.0                    NaN               NaN  79.050000
max               0.0                    NaN               NaN  87.700000

In [89]:
total_nuevo=total_total.drop(["MEASURE","Unit Code","Flags","Measure","INEQUALITY","LOCATION", "PowerCode Code","Reference Period Code","Flag Codes","Reference Period","PowerCode","Unit"],axis=1)
pd.DataFrame(total_nuevo)

                    Country                            Indicator  Value
Inequality
Total             Australia  Feeling safe walking alone at night   63.6
Total               Austria  Feeling safe walking alone at night   80.7
Total               Belgium  Feeling safe walking alone at night   70.7
Total                Canada  Feeling safe walking alone at night   80.9
Total        Czech Republic  Feeling safe walking alone at night   68.3
Total               Denmark  Feeling safe walking alone at night   83.0
Total               Finland  Feeling safe walking alone at night   82.9
Total                France  Feeling safe walking alone at night   69.6
Total               Germany  Feeling safe walking alone at night   75.9
Total                Greece  Feeling safe walking alone at night   61.8
Total               Hungary  Feeling safe walking alone at night   50.7
Total               Iceland  Feeling safe walking alone at night   87.0
Total               Ireland  Feeling safe walking alone at night   75.5
Total                 Italy  Feeling safe walking alone at night   58.3
Total                 Japan  Feeling safe walking alone at night   70.6
Total                 Korea  Feeling safe walking alone at night   63.9
Total            Luxembourg  Feeling safe walking alone at night   72.0
Total                Mexico  Feeling safe walking alone at night   45.9
Total           Netherlands  Feeling safe walking alone at night   81.2
Total           New Zealand  Feeling safe walking alone at night   64.8
Total                Norway  Feeling safe walking alone at night   87.7
Total                Poland  Feeling safe walking alone at night   66.3
Total              Portugal  Feeling safe walking alone at night   72.1
Total       Slovak Republic  Feeling safe walking alone at night   60.1
Total                 Spain  Feeling safe walking alone at night   83.1
Total                Sweden  Feeling safe walking alone at night   75.9
Total           Switzerland  Feeling safe walking alone at night   84.0
Total                Turkey  Feeling safe walking alone at night   60.6
Total        United Kingdom  Feeling safe walking alone at night   77.4
Total         United States  Feeling safe walking alone at night   74.1
Total                Brazil  Feeling safe walking alone at night   37.3
Total                 Chile  Feeling safe walking alone at night   51.1
Total               Estonia  Feeling safe walking alone at night   67.2
Total                Israel  Feeling safe walking alone at night   70.2
Total                Latvia  Feeling safe walking alone at night   60.7
Total                Russia  Feeling safe walking alone at night   52.2
Total              Slovenia  Feeling safe walking alone at night   84.7
Total          South Africa  Feeling safe walking alone at night   36.1
Total          OECD - Total  Feeling safe walking alone at night   68.6

In [90]:

#parámetro PARA CAMINAR SEGURO
Promedio_caminar_seguro=68.63
total=total_nuevo.count()
print(total)
caminar_nuevo=total_nuevo["Value"]

Country      39
Indicator    39
Value        39
dtype: int64

In [92]:
P_C=sum(caminar_nuevo>Promedio_caminar_seguro)
Promedio_total=P_C/total

print("Existen", P_C,"paises donde se sienten seguros al caminar", "de un total de",total)

Existen 21 paises donde se sienten seguros al caminar de un total de Country      39
Indicator    39
Value        39
dtype: int64

In [98]:
caminar_arriba_media=total_nuevo[total_nuevo["Value"]>68.63]
caminar_orden=total_nuevo.sort_values(by=["Value"], axis=0, ascending=False)
pd.DataFrame(caminar_orden)

                    Country                            Indicator  Value
Inequality
Total                Norway  Feeling safe walking alone at night   87.7
Total               Iceland  Feeling safe walking alone at night   87.0
Total              Slovenia  Feeling safe walking alone at night   84.7
Total           Switzerland  Feeling safe walking alone at night   84.0
Total                 Spain  Feeling safe walking alone at night   83.1
Total               Denmark  Feeling safe walking alone at night   83.0
Total               Finland  Feeling safe walking alone at night   82.9
Total           Netherlands  Feeling safe walking alone at night   81.2
Total                Canada  Feeling safe walking alone at night   80.9
Total               Austria  Feeling safe walking alone at night   80.7
Total        United Kingdom  Feeling safe walking alone at night   77.4
Total               Germany  Feeling safe walking alone at night   75.9
Total                Sweden  Feeling safe walking alone at night   75.9
Total               Ireland  Feeling safe walking alone at night   75.5
Total         United States  Feeling safe walking alone at night   74.1
Total              Portugal  Feeling safe walking alone at night   72.1
Total            Luxembourg  Feeling safe walking alone at night   72.0
Total               Belgium  Feeling safe walking alone at night   70.7
Total                 Japan  Feeling safe walking alone at night   70.6
Total                Israel  Feeling safe walking alone at night   70.2
Total                France  Feeling safe walking alone at night   69.6
Total          OECD - Total  Feeling safe walking alone at night   68.6
Total        Czech Republic  Feeling safe walking alone at night   68.3
Total               Estonia  Feeling safe walking alone at night   67.2
Total                Poland  Feeling safe walking alone at night   66.3
Total           New Zealand  Feeling safe walking alone at night   64.8
Total                 Korea  Feeling safe walking alone at night   63.9
Total             Australia  Feeling safe walking alone at night   63.6
Total                Greece  Feeling safe walking alone at night   61.8
Total                Latvia  Feeling safe walking alone at night   60.7
Total                Turkey  Feeling safe walking alone at night   60.6
Total       Slovak Republic  Feeling safe walking alone at night   60.1
Total                 Italy  Feeling safe walking alone at night   58.3
Total                Russia  Feeling safe walking alone at night   52.2
Total                 Chile  Feeling safe walking alone at night   51.1
Total               Hungary  Feeling safe walking alone at night   50.7
Total                Mexico  Feeling safe walking alone at night   45.9
Total                Brazil  Feeling safe walking alone at night   37.3
Total          South Africa  Feeling safe walking alone at night   36.1

###Muestra las columnas de los datos completos de los países con mejor satisfacción de vida.####

In [101]:
OCDE7=OCDE
OCDE_satis=OCDE7.set_index("INDICATOR")
variable_1=OCDE_satis.loc["SW_LIFS"]
pd.DataFrame(variable_1)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
INDICATOR,,,,,,,,,,,,,,,,
SW_LIFS,AUS,Australia,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
SW_LIFS,AUT,Austria,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
SW_LIFS,BEL,Belgium,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
SW_LIFS,CAN,Canada,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
SW_LIFS,CZE,Czech Republic,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
SW_LIFS,DNK,Denmark,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
SW_LIFS,FIN,Finland,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
SW_LIFS,FRA,France,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
SW_LIFS,DEU,Germany,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
SW_LIFS,GRC,Greece,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,HUN,Hungary,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
SW_LIFS,ISL,Iceland,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
SW_LIFS,IRL,Ireland,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
SW_LIFS,ITA,Italy,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
SW_LIFS,JPN,Japan,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
SW_LIFS,KOR,Korea,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
SW_LIFS,LUX,Luxembourg,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
SW_LIFS,MEX,Mexico,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
SW_LIFS,NLD,Netherlands,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
SW_LIFS,NZL,New Zealand,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
SW_LIFS,NOR,Norway,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
SW_LIFS,POL,Poland,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
SW_LIFS,PRT,Portugal,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,SVK,Slovak Republic,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.1,NaN,NaN
SW_LIFS,ESP,Spain,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
SW_LIFS,SWE,Sweden,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
SW_LIFS,CHE,Switzerland,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
SW_LIFS,TUR,Turkey,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
SW_LIFS,GBR,United Kingdom,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.7,NaN,NaN
SW_LIFS,USA,United States,Life satisfaction,L,Value,TOT,Total,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SW_LIFS,FIN,Finland,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.1,NaN,NaN
SW_LIFS,FRA,France,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.1,NaN,NaN
SW_LIFS,DEU,Germany,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
SW_LIFS,GRC,Greece,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.3,NaN,NaN
SW_LIFS,HUN,Hungary,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN
SW_LIFS,ISL,Iceland,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
SW_LIFS,IRL,Ireland,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.8,NaN,NaN
SW_LIFS,ITA,Italy,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
SW_LIFS,JPN,Japan,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
SW_LIFS,KOR,Korea,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.1,NaN,NaN
SW_LIFS,LUX,Luxembourg,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
SW_LIFS,MEX,Mexico,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.1,NaN,NaN
SW_LIFS,NZL,New Zealand,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.2,NaN,NaN
SW_LIFS,NOR,Norway,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
SW_LIFS,POL,Poland,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,PRT,Portugal,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.5,NaN,NaN
SW_LIFS,SVK,Slovak Republic,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.7,NaN,NaN
SW_LIFS,ESP,Spain,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.2,NaN,NaN
SW_LIFS,SWE,Sweden,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
SW_LIFS,CHE,Switzerland,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,7.1,NaN,NaN
SW_LIFS,TUR,Turkey,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,GBR,United Kingdom,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
SW_LIFS,BRA,Brazil,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,6.5,NaN,NaN
SW_LIFS,CHL,Chile,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
SW_LIFS,EST,Estonia,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,LVA,Latvia,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.4,NaN,NaN
SW_LIFS,RUS,Russia,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.7,NaN,NaN
SW_LIFS,SVN,Slovenia,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
SW_LIFS,ZAF,South Africa,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,4.2,NaN,NaN
SW_LIFS,OECD,OECD - Total,Life satisfaction,L,Value,LW,Low,AVSCORE,Average score,0,Units,NaN,NaN,5.9,E,Estimated value

In [89]:
variable_1.describe()

       PowerCode Code  Reference Period Code  Reference Period       Value
count           188.0                    0.0               0.0  188.000000
mean              0.0                    NaN               NaN    6.543085
std               0.0                    NaN               NaN    0.824170
min               0.0                    NaN               NaN    4.200000
25%               0.0                    NaN               NaN    5.900000
50%               0.0                    NaN               NaN    6.600000
75%               0.0                    NaN               NaN    7.300000
max               0.0                    NaN               NaN    8.000000

In [104]:
total_población1=variable_1.set_index("Inequality")

In [105]:
total_satisfacción_de_vida=total_población1.loc["Total"]
pd.DataFrame(total_satisfacción_de_vida)

,LOCATION,Country,Indicator,MEASURE,Measure,INEQUALITY,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
Inequality,,,,,,,,,,,,,,,
Total,AUS,Australia,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
Total,AUT,Austria,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
Total,BEL,Belgium,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
Total,CAN,Canada,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
Total,CZE,Czech Republic,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
Total,DNK,Denmark,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
Total,FIN,Finland,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
Total,FRA,France,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
Total,DEU,Germany,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
Total,GRC,Greece,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
Total,HUN,Hungary,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.3,NaN,NaN
Total,ISL,Iceland,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
Total,IRL,Ireland,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.0,NaN,NaN
Total,ITA,Italy,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
Total,JPN,Japan,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
Total,KOR,Korea,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
Total,LUX,Luxembourg,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
Total,MEX,Mexico,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
Total,NLD,Netherlands,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.4,NaN,NaN
Total,NZL,New Zealand,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
Total,NOR,Norway,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
Total,POL,Poland,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
Total,PRT,Portugal,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.2,NaN,NaN
Total,SVK,Slovak Republic,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.1,NaN,NaN
Total,ESP,Spain,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.4,NaN,NaN
Total,SWE,Sweden,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.3,NaN,NaN
Total,CHE,Switzerland,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.5,NaN,NaN
Total,TUR,Turkey,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.5,NaN,NaN
Total,GBR,United Kingdom,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.7,NaN,NaN
Total,USA,United States,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.9,NaN,NaN
Total,BRA,Brazil,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.6,NaN,NaN
Total,CHL,Chile,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.7,NaN,NaN
Total,EST,Estonia,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.6,NaN,NaN
Total,ISR,Israel,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,7.2,NaN,NaN
Total,LVA,Latvia,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.9,NaN,NaN
Total,RUS,Russia,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.0,NaN,NaN
Total,SVN,Slovenia,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,5.8,NaN,NaN
Total,ZAF,South Africa,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,4.8,NaN,NaN
Total,OECD,OECD - Total,Life satisfaction,L,Value,TOT,AVSCORE,Average score,0,Units,NaN,NaN,6.5,NaN,NaN

In [106]:

total_satisfacción_de_vida.describe()

       PowerCode Code  Reference Period Code  Reference Period      Value
count            39.0                    0.0               0.0  39.000000
mean              0.0                    NaN               NaN   6.528205
std               0.0                    NaN               NaN   0.766039
min               0.0                    NaN               NaN   4.800000
25%               0.0                    NaN               NaN   5.900000
50%               0.0                    NaN               NaN   6.600000
75%               0.0                    NaN               NaN   7.250000
max               0.0                    NaN               NaN   7.500000

In [107]:
nuevo_satisfacción=total_satisfacción_de_vida.drop(["MEASURE","Unit Code","Flags","Measure","INEQUALITY","LOCATION", "PowerCode Code","Reference Period Code","Flag Codes","Reference Period","PowerCode","Unit"],axis=1)
pd.DataFrame(total_nuevo)

                    Country                            Indicator  Value
Inequality
Total             Australia  Feeling safe walking alone at night   63.6
Total               Austria  Feeling safe walking alone at night   80.7
Total               Belgium  Feeling safe walking alone at night   70.7
Total                Canada  Feeling safe walking alone at night   80.9
Total        Czech Republic  Feeling safe walking alone at night   68.3
Total               Denmark  Feeling safe walking alone at night   83.0
Total               Finland  Feeling safe walking alone at night   82.9
Total                France  Feeling safe walking alone at night   69.6
Total               Germany  Feeling safe walking alone at night   75.9
Total                Greece  Feeling safe walking alone at night   61.8
Total               Hungary  Feeling safe walking alone at night   50.7
Total               Iceland  Feeling safe walking alone at night   87.0
Total               Ireland  Feeling safe walking alone at night   75.5
Total                 Italy  Feeling safe walking alone at night   58.3
Total                 Japan  Feeling safe walking alone at night   70.6
Total                 Korea  Feeling safe walking alone at night   63.9
Total            Luxembourg  Feeling safe walking alone at night   72.0
Total                Mexico  Feeling safe walking alone at night   45.9
Total           Netherlands  Feeling safe walking alone at night   81.2
Total           New Zealand  Feeling safe walking alone at night   64.8
Total                Norway  Feeling safe walking alone at night   87.7
Total                Poland  Feeling safe walking alone at night   66.3
Total              Portugal  Feeling safe walking alone at night   72.1
Total       Slovak Republic  Feeling safe walking alone at night   60.1
Total                 Spain  Feeling safe walking alone at night   83.1
Total                Sweden  Feeling safe walking alone at night   75.9
Total           Switzerland  Feeling safe walking alone at night   84.0
Total                Turkey  Feeling safe walking alone at night   60.6
Total        United Kingdom  Feeling safe walking alone at night   77.4
Total         United States  Feeling safe walking alone at night   74.1
Total                Brazil  Feeling safe walking alone at night   37.3
Total                 Chile  Feeling safe walking alone at night   51.1
Total               Estonia  Feeling safe walking alone at night   67.2
Total                Israel  Feeling safe walking alone at night   70.2
Total                Latvia  Feeling safe walking alone at night   60.7
Total                Russia  Feeling safe walking alone at night   52.2
Total              Slovenia  Feeling safe walking alone at night   84.7
Total          South Africa  Feeling safe walking alone at night   36.1
Total          OECD - Total  Feeling safe walking alone at night   68.6

In [109]:
#parámetro para satisfacción de vida
satisfacción_vida_promedio=6.52
total=nuevo_satisfacción.count()
satisfacción1=nuevo_satisfacción["Value"]-1

In [112]:
P_S=sum(satisfacción1>satisfacción_vida_promedio)
Promedio_total=P_S/total

print("Existen", P_S,"paises donde se sienten seguros al caminar", "de un total de",total)

Existen 0 paises donde se sienten seguros al caminar de un total de Country      39
Indicator    39
Value        39
dtype: int64

In [113]:
satisfacción_arriba_media=nuevo_satisfacción[nuevo_satisfacción["Value"]>6.52]
satisfacción_orden=total_nuevo.sort_values(by=["Value"], axis=0, ascending=False)
pd.DataFrame(caminar_orden)

                    Country                            Indicator  Value
Inequality
Total                Norway  Feeling safe walking alone at night   87.7
Total               Iceland  Feeling safe walking alone at night   87.0
Total              Slovenia  Feeling safe walking alone at night   84.7
Total           Switzerland  Feeling safe walking alone at night   84.0
Total                 Spain  Feeling safe walking alone at night   83.1
Total               Denmark  Feeling safe walking alone at night   83.0
Total               Finland  Feeling safe walking alone at night   82.9
Total           Netherlands  Feeling safe walking alone at night   81.2
Total                Canada  Feeling safe walking alone at night   80.9
Total               Austria  Feeling safe walking alone at night   80.7
Total        United Kingdom  Feeling safe walking alone at night   77.4
Total               Germany  Feeling safe walking alone at night   75.9
Total                Sweden  Feeling safe walking alone at night   75.9
Total               Ireland  Feeling safe walking alone at night   75.5
Total         United States  Feeling safe walking alone at night   74.1
Total              Portugal  Feeling safe walking alone at night   72.1
Total            Luxembourg  Feeling safe walking alone at night   72.0
Total               Belgium  Feeling safe walking alone at night   70.7
Total                 Japan  Feeling safe walking alone at night   70.6
Total                Israel  Feeling safe walking alone at night   70.2
Total                France  Feeling safe walking alone at night   69.6
Total          OECD - Total  Feeling safe walking alone at night   68.6
Total        Czech Republic  Feeling safe walking alone at night   68.3
Total               Estonia  Feeling safe walking alone at night   67.2
Total                Poland  Feeling safe walking alone at night   66.3
Total           New Zealand  Feeling safe walking alone at night   64.8
Total                 Korea  Feeling safe walking alone at night   63.9
Total             Australia  Feeling safe walking alone at night   63.6
Total                Greece  Feeling safe walking alone at night   61.8
Total                Latvia  Feeling safe walking alone at night   60.7
Total                Turkey  Feeling safe walking alone at night   60.6
Total       Slovak Republic  Feeling safe walking alone at night   60.1
Total                 Italy  Feeling safe walking alone at night   58.3
Total                Russia  Feeling safe walking alone at night   52.2
Total                 Chile  Feeling safe walking alone at night   51.1
Total               Hungary  Feeling safe walking alone at night   50.7
Total                Mexico  Feeling safe walking alone at night   45.9
Total                Brazil  Feeling safe walking alone at night   37.3
Total          South Africa  Feeling safe walking alone at night   36.1

##### Gráficas###